version: 2.1

executors:
  py35:
    docker: [image: python:3.5-slim]
  py36:
    docker: [image: python:3.6-slim]
  py37:
    docker: [image: python:3.7-slim]

workflows:
  version: 2
  test:
    jobs:
      - test-35
      - test-36
      - test-37
  lint:
    jobs:
      - lint

jobs:
  test-35:
    executor: py35
    steps:
      - checkout
      - test
  test-36:
    executor: py36
    steps:
      - checkout
      - test
  test-37:
    executor: py37
    steps:
      - checkout
      - test
  lint:
    executor: py37
    steps:
      - checkout
      - lint

commands:
  setup:
    steps:
      - run: pip install -U pip wheel setuptools tox flit
  install-local:
    steps:
      - run: make install
  tox:
    steps:
      - run: tox --skip-missing-interpreters
  test:
    steps:
      - setup
      - tox
  lint:
    steps:
      - setup
      - install-local
      - run: make lint
